### ISSUE TITLE
 Spanish as the default language for fundamentals/localization.rst "Globalization and localization"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1798] opened 2016-08-19 23:27 UTC
I want to use Spanish as the default language of my application and English as optional. I configured it all up. If I have two separate resx files for both Spanish and English the website runs as expected. But I don't want to include Spanish resx file, I want use the in-code strings (ie. Localizer). When I only include English resx file, the website uses it, ignores in-code strings.

**Comment by Rick-Anderson** [comment] 2016-08-19 23:28
@ryanbrandenburg 
I want to use Spanish as the default language of my application and English as optional. I configured it all up. If I have two separate resx files for both Spanish and English the website runs as expected. But I don't want to include Spanish resx file, I want use the in-code strings (ie. Localizer). When I only include English resx file, the website uses it, ignores in-code strings.

**Comment by Rick-Anderson** [comment] 2016-08-19 23:31
@ryanbrandenburg  can you check the answer at https://docs.asp.net/en/latest/fundamentals/localization.html#comment-2842901156
Looks like that might solve the problem.

**Comment by Rick-Anderson** [comment] 2016-08-22 13:41
opened https://github.com/aspnet/Localization/issues/277

**Comment by SherleyDev** [comment] 2016-08-22 19:05
I think the problem is that I don't use cookies. I use URL friendly localization. http://localhost/es/account/login or http://localhost/accont/login for Spanish and http://localhost/en/account/login for English.

For URL friendly localization I follow the method described in this SO answer: http://stackoverflow.com/questions/35829426/optionally-override-request-culture-via-url-route-in-an-asp-net-core-1-0-applica

Thank you!

**Comment by ryanbrandenburg** [comment] 2016-08-22 21:13
Yes, if you want to do URL localization (or anything other than Query string, cookie or Accept header_ then you'll have to do some manual setup, as they did in the SO question linked here.

I'll close this one out as it seems resolved.

**Closed by ryanbrandenburg** 2016-08-22 21:13 UTC
Labels: question
