### ISSUE TITLE
Syntax error on line 3

### ISSUE THREAD

**Issue by DedicatedManagers** [aspnet/Docs#9853] opened 2018-12-05 20:24 UTC
When I try the config test, I get the following error:
[root@as6 logs]# service httpd configtest
AH00526: Syntax error on line 3 of /etc/httpd/conf.d/vhost.giveovation.com.conf:
Unrecognized header format %

That error corresponds to the % sign below.
&lt;VirtualHost :&gt;
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
&lt;/VirtualHost&gt;

From research (https://serverfault.com/questions/748326/apache-2-4-unrecognized-header-format), this appears to be a version issue and requires Apache 2.4.10 or higher.  

I am on Centos 7 and it appears the latest version I can get is 2.4.6.  Is there another way to write this RequestHeader directive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **spboyer**

**Comment by guardrex** [comment] 2018-12-05 21:16
@shirhatti

**Comment by guardrex** [comment] 2018-12-05 21:20
@DedicatedManagers I'm not knowledgeable on this platform, but I caught wind from online posts of this: Does `$scheme` work there in place of `%{REQUEST_SCHEME}`?

**Comment by shirhatti** [comment] 2018-12-06 19:43
Dupe of https://github.com/aspnet/Docs/issues/6827#issuecomment-396754152

**Comment by shirhatti** [comment] 2018-12-06 19:44
Pasting in my earlier response:

> The options I see are either:

> See if there is a vendor supported way of installing Apache >= 2.4.10
> Let the reader figure it out for themselves

**Comment by guardrex** [comment] 2018-12-06 19:51
Thanks @shirhatti 

This doesn't seem actionable from a docs perspective. We can't say how to address the first option, and the second option is how things stand today. I'll close since there isn't anything we can do here.

**Closed by guardrex** 2018-12-06 19:51 UTC
Labels: P4, Source - Docs.ms, support-request

**Comment by DedicatedManagers** [comment] 2018-12-10 21:52
Thanks.  $scheme does seem to work.... at least its not giving an error.  ... I'm setting this up for another developer of the project so I'll report back if it's actually working.
