### ISSUE TITLE
handshake timeout is not very clear 

### ISSUE THREAD

**Issue by Arash-Sabet** [aspnet/Docs#7691] opened 2018-07-19 13:50 UTC
The meaning of handshake timeout is not very clear e.g. how it works and why it is required. The nature of timeouts whether they're seconds, milliseconds, minute need to be clearly stated in the table(s) where they're described. You need also to clarify what are the default values of both client and server timeouts and how they are configured when they relate to each other in the same application. Please have a freshe-eye person without previous exposure to signalR read this document, come up with a list of question and have you guys include the answers in this document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment] 2018-07-20 18:29
@anurse please propose update

**Comment by anurse** [comment] 2018-07-20 18:34
We can clarify the concept of Handshake for sure. As for the units, if you look at the actual property it's a `System.TimeSpan` which allows you to configure whichever units you want.

**Comment by anurse** [comment] 2018-07-20 18:35
@Arash-Sabet Please use exactly this process to file any questions! We need exactly this kind of feedback, as you observed since we're all quite familiar with SignalR :)

**Comment by Arash-Sabet** [comment] 2018-07-20 18:44
@anurse Here are the areas that I'd like to be amended:

- The handshake process needs certainly to be clarified.
- The document should clearly state which entries are TimeSpan.FromMinutes(..) and TimeSpan.FromSeconds(..) and why not both of them are not implemented as milliseconds? Why would a developer think about supplying a value in seconds, somewhere else in minutes, etc?
- Why cannot one configure HandshakeTimeout in JavaScript?
- The following paragraph is confusing as it's not clear whether the last statement applies to JavaScript client only or it may be applicable to .NET client too?

> In the .NET Client, timeout values are specified as TimeSpan values. In the JavaScript client, timeout values are specified as numbers. The numbers represent time values in milliseconds.

These are the immediate areas that caught my eyes. It will be way cleaner you guys to consider changing all timeout values in both client and server sides to milliseconds for consistency sake.

Cheers!

**Comment by anurse** [comment] 2018-07-20 19:09
> The handshake process needs certainly to be clarified.

This is specified in the [Hub Protocol Spec](https://github.com/aspnet/SignalR/blob/release/2.2/specs/HubProtocol.md). The handshake process is not intended to be a user concern, it's something developers of custom clients will need to be aware of, and the timeout may need to be configured in the case of severe network latency. I've updated the doc to reflect that.

> The document should clearly state which entries are TimeSpan.FromMinutes(..) and TimeSpan.FromSeconds(..)

I'm confused by this. You pass a `TimeSpan` that **you** create in to these properties, so you can use any of `FromMinutes`, `FromSeconds`, etc. to specify it. That's generally how timeout values in .NET code are specified, since it provides more clarity around the units.

> Why cannot one configure HandshakeTimeout in JavaScript?

Simply due to a lack of resources during our initial release. Feel free to file a bug if you have a need to configure this. Are you seeing issues with handshake timeout in your application?

> The following paragraph is confusing as it's not clear whether the last statement applies to JavaScript client only or it may be applicable to .NET client too

I'll clarify that. Only the first statement applies to .NET.

**Comment by Arash-Sabet** [comment] 2018-07-20 19:13
@anurse Thanks for the reply.

> Simply due to a lack of resources during our initial release. Feel free to file a bug if you have a need to configure this. Are you seeing issues with handshake timeout in your application?

No, so far no issues but we'll monitor.

**Comment by anurse** [comment] 2018-07-20 19:18
Ok, then I would not worry about this setting at all. It's only there because we don't like having hard-coded limits and timeouts. There's no reason a user should have to configure this setting unless they are in a very specific kind of environment where there is consistent, severe (measured in seconds, not milliseconds 😄), latency. That's how I've updated the docs, to indicate that this isn't a setting a user should expect to need to configure.

**Comment by Arash-Sabet** [comment] 2018-07-20 19:22
@anurse Just wondering, are there any rules behind HubOptions (the server side)? For e.g. HanshakeTimeout can be greater (or smaller) than KeepAliveInterval? That would be cool to have a logical check when setting those options to catch misconfigurations rather waiting to see the things timeout or get disconnected unexpectedly.

**Comment by Rick-Anderson** [comment] 2018-09-06 23:11
@tdykstra  can you work on this in sprint 141?

**Comment by tdykstra** [comment] 2018-09-06 23:14
yes

**Comment by tdykstra** [comment] 2018-09-08 19:38
@Rick-Anderson The doc updates for this were already done in #7710.  There is one final question awaiting an answer from @anurse that might result in additional changes.

**Comment by anurse** [comment] 2018-09-13 17:49
> Just wondering, are there any rules behind HubOptions (the server side)?

That's pretty much it, as far as I'm aware.

> That would be cool to have a logical check when setting those options to catch misconfigurations

The problem is caused by a client configuration value being inconsistent with a server one so we can't really detect this case and throw an error since the configuration is not shared between the two parties.

**Comment by tdykstra** [comment] 2018-09-13 18:30
@Arash-Sabet Thanks for working with us to get helpful information added to the docs!  Since the issue was addressed by PR #7710, I'm closing it.  If we missed something, or something new comes up on this topic, we can reopen it.

**Closed by tdykstra** 2018-09-13 18:30 UTC
Labels: Source - Docs.ms

**Comment by ogomaemmanuel** [comment] 2018-10-07 16:03
Currently, when I use signalR locally everything works well, but when I host it in production, it does not work even though the connection is being established. On production i get timeout warning.

**Comment by anurse** [comment] 2018-10-08 15:07
I don't think that's related to this issue though. Can you file a New Issue on https://github.com/aspnet/SignalR/issues with details about how your production environment differs from your development environment and what errors you are seeing?
