### ISSUE TITLE
signalr/hubs Code from outside the Hub class

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#5963] opened 2018-04-13 13:44 UTC
A customer comment from Glen95 on the https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1 doc:

"It would be very helpful if you could add a section similar to https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-call-client-methods-and-manage-groups-from-outside-the-hub-class  that explains "How to call client methods and manage groups from outside the Hub class"

@anurse Do we want to add this to docs? This could go here or in the doc on Groups when we author it. Groups doc proposed outline: https://github.com/aspnet/Docs/issues/5910

**Comment by anurse** [comment] 2018-04-13 16:30
Duplicate of #5493

**Closed** 2018-04-13 16:47 UTC
