### ISSUE TITLE
Issues (with services.AddSignalR())

### ISSUE THREAD

**Issue by Nickeron** [aspnet/Docs#6340] opened 2018-05-10 18:13 UTC
services.AddSignalR(); does not work, and I could not figure out how to fix it.
using Microsoft (.AspNetCore) -> .AspNet .SignalR;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778aaeae-2fa8-fb73-b644-8e99ee06398e
* Version Independent ID: 159a95c8-7afd-bb03-fdfc-2323559ef50a
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/signalr/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/get-started.md)
* Service: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment] 2018-05-10 18:26
@Nickeron can you elaborate on how it doesn't work? I can't repo the problem and we've had many people report success.

**Comment by ImageQC** [comment] 2018-05-11 01:45
I had the same problem:

`        public void ConfigureServices(IServiceCollection services)
        {
...
            services.AddSignalR();
        }`

AddSignalR() isn't a method of services.

FIX:

You need to install .NET Core SDK 2.1.300-preview1

https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1 

It should then work. I hope this helps.

**Comment by Rick-Anderson** [comment] 2018-05-11 01:46
@ImageQC  Thanks for reporting the solution.

@rachelappel  can you get this fixed Friday morning?

**Comment by ImageQC** [comment] 2018-05-11 10:15
Brand new project following your recipe exactly like it was the sainted Mary Berry's lemon drizzle cake ;-)

**Comment by rachelappel** [comment] 2018-05-11 10:35
@ImageQC Is it erroring, and if so, what is the error message?

**Comment by ImageQC** [comment] 2018-05-11 10:42
In my case installing .NET Core SDK 2.1.300-preview1 fixed the problem as reported above. However, the sample didn't work as reported https://github.com/aspnet/Docs/issues/6358. The error message was Failed to start the connection. Error: Unable to initialize any of the available transports

**Comment by rachelappel** [comment] 2018-05-11 10:54
@ImageQC What results are you getting in the sample?
Can you print out the <PackageReference> elements from your .csproj file?

**Comment by ImageQC** [comment] 2018-05-11 11:10
The source of the problem is the lack of control over package versions. I got the sample working at

- https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/ChatRoomLocal

The packages are given below. However, God knows where signalr.js comes from as the authors didn't bother to put a version number in the file (a sackable offence in my day). I just copied it and the rest of the script folder into my SpikeWebApp. Perhaps, you could find out and post here. Is this code developed by Microsoft employees, or volunteers?

![image](https://user-images.githubusercontent.com/23079073/39921812-e9eae176-5539-11e8-85f6-8a0b8b79b20e.png)

**Comment by rachelappel** [comment] 2018-05-11 11:14
@ImageQC What about the Getting Started sample? Are you having issues with that sample?

**Comment by ImageQC** [comment] 2018-05-11 11:25
I hope all this was helpful.

**Comment by rachelappel** [comment] 2018-05-11 11:27
I don't understand what "a shame to encourage others" has to do with this issue?

**Comment by Rick-Anderson** [comment] 2018-05-11 17:48
Shouldn't the *.csproj* file be:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

**Comment by rachelappel** [comment] 2018-05-11 20:55
@Rick-Anderson That's what's in the sample.

**Comment by Rick-Anderson** [comment] 2018-05-11 21:40
> God knows where signalr.js comes from as the authors didn't bother to put a version number in the file (a sackable offence in my day).

It uses the latest version from your NuGet source. I'm getting clarification from the product team on why they are using this approach.

**Comment by whizkidwwe1217** [comment] 2018-05-13 14:02
@Rabadash8820 @rachelappel I'm getting 404 at https://localhost:5001/charthub/negotiate? Do you guys have any idea how to fix it?

**Comment by davidfowl** [comment] 2018-05-13 20:36
You should be using ASP.NET Core 2.1 rc1. I wouldn't update the docs to show that as we don't talk abut explicit package references to for example, add MVC.

If we do explain that AddMvc is in the Microsoft.AspNetCore.Mvc package then I'd be more receptive to a change like this. 

Maybe the SignalR guide needs to explain say "follow the migration guide to upgrade to ASP.NET Core 2.1"

**Comment by ImageQC** [comment] 2018-05-14 03:56
I wasted most of the day trying to get it to work with ASP.NET Core 2.1, but failed due to package version conflicts. The information given in your docs just isn't sufficient. You need to give the .CSPPROJ details, as I did above. I would be delighted if you could give the information needed for me to target Core 2.1, but  I started at Core 2.0 on the basis that you need first get the project working and then make your changes. I hope others following your example find the info I provided useful. However, my advice would be to go to the Azure SignalR group. Their sample does work out of the box. Yours should do the same, yes?

https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/ChatRoomLocal

**Comment by ImageQC** [comment] 2018-05-14 12:17
>> The doc says in the very first paragraph: .NET Core 2.1.0 RC1 SDK

You will note that I created a post about just that issue, even containing a link to the download. However, having done that and updated VS2017 to 15.7.1, the samples still didn't work. The problem seems to relate to package incompatibility. Eventually I found a set of packages that did work, but unfortunately only with .NET Core App 2.0. Therefore I posted my .CSPROJ to help anyone else who was struggling with this issue. I rather hoped that the owner and contributors (Microsoft staff?) would then post an update to the .CSPROJ with the required packages for  .NET Core App 2.1. Unfortunately, that doesn't seem to have happened yet.

Feedback: Modern software development is not much more than following recipes, so you need to make sure the recipes actually work. It would be very helpful the MS teams creating samples paid more attention to:

1) Rigorously control their dev environment
2) Testing the samples in that environment before publishing
3) Giving exact details of the environment, particularly the .CSPROJ content

I hope everyone can learn from this.

**Comment by ImageQC** [comment] 2018-05-15 02:14
Glad to hear you found my feedback useful. If the samples are now working and you've detailed the packages people need to use then we can close this issue, yes?

**Closed** 2018-05-17 11:25 UTC
Labels: Source - Docs.ms

**Comment by 8enSmith** [comment] 2019-07-03 23:50
> > 1. Rigorously control their dev environment
> > 2. Testing the samples in that environment before publishing
> > 3. Giving exact details of the environment, particularly the .CSPROJ content
> 
> All of that is done automatically with the template generated code. The templates use `<PackageReference Include="Microsoft.AspNetCore.App" />` which bring in the right NuGet packages.

As well as specifying the package reference stated above I also had to change the target framework to 2.1 to get this demo project working i.e.

<TargetFramework>netcoreapp2.1</TargetFramework>

Hope that will help anyone else who found it frustrating getting this demo project working!
