### ISSUE TITLE
Routing doc missing attribute routes?

### ISSUE THREAD

**Issue by pebezo** [aspnet/Docs#1179] opened 2016-05-02 02:53 UTC
https://docs.asp.net/en/latest/fundamentals/routing.html

In the recommendations section (bottom of the document):

> Attribute routes should be used for all APIs.
> Attribute routes are recommended for when you need complete control over your app’s URLs.

If you search the page, this is the only place where "attribute routes" are mentioned... We'd probably need an example. Also, what's the difference between these and MapRoute? Why should we use attribute routes for all APIs? How can we debug routes? Is there a way to output the routing table?

**Comment by ardalis** [comment] 2016-05-02 12:23
#117 will cover Attribute routes, and we'll link to it once it's there, I think. Your other points would all make good additions to the article, though, I think.

**Comment by danroth27** [comment] 2016-05-02 20:38
Duplicate of #117

**Closed by danroth27** 2016-05-02 20:38 UTC
