### ISSUE TITLE
Double quotes missing

### ISSUE THREAD

**Issue by marvinnagaguerrero** [aspnet/Docs#7343] opened 2018-06-28 05:37 UTC
if this      npm install @aspnet/signalr     fails.
use          npm install "@aspnet/signalr"    instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by scottaddie** [comment] 2018-06-28 18:20
@marvinnagaguerrero Which command shell are you using when this fails?

**Comment by nbarbettini** [comment] 2018-07-01 23:54
FWIW, `npm install @aspnet/signalr` works for me in PowerShell.

**Comment by scottaddie** [comment] 2018-07-05 20:47
Closing, as I'm unable to reproduce.

**Closed by scottaddie** 2018-07-05 20:47 UTC
Labels: Source - Docs.ms
