### ISSUE TITLE
doc WebSockets for 1.1

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2789] opened 2017-02-16 22:51 UTC
see https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/

- [x ] Short term, add to What's new in ASP.NET Core 1.1 #2786
- [ ] Long term, create an independent doc

**Comment by Rick-Anderson** [comment] 2017-02-16 22:52
@tdykstra  this got missed. Can you do this one?

**Comment by tdykstra** [comment] 2017-02-16 23:12
@Rick-Anderson What's the priority compared to csproj work?

**Comment by Rick-Anderson** [comment] 2017-02-16 23:14
@tdykstra  this is higher. We just need a copy of the announcement for now.

**Comment by tdykstra** [comment] 2017-03-15 15:26
Duplicate of #204

**Closed by tdykstra** 2017-03-15 15:26 UTC
Labels: P1
