### ISSUE TITLE
Should mention java client

### ISSUE THREAD

**Issue by BrianChesbrough** [aspnet/Docs#11626] opened 2019-03-21 19:00 UTC
.NET and other clients section should mention the Java Client that now exists. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by scottaddie** [comment] 2019-03-21 19:41
Closing as duplicate of https://github.com/aspnet/Docs/issues/11627

**Closed by scottaddie** 2019-03-21 19:41 UTC
Labels: SignalR, Source - Docs.ms
