### ISSUE TITLE
signalr/groups Manage Groups in ASP.NET Core SignalR

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#5910] opened 2018-04-09 21:10 UTC
Outline:

•	Add and remove users
(use User.Identity rather than connection id)
•	Message members of group
•	Store group membership in SQL Table
•	Store group membership in Azure Table
•	Verify group membership when reconnecting

**Comment by anurse** [comment] 2018-05-31 20:04
Here are the notes from the Groups and Users issue I filed and closed as a dupe of this.

* Groups
  * Use Groups to manage collections of connections you want to be able to broadcast to
  * It's not possible to enumerate or count the members of a group (because each server only knows about it's own connections, not those on other servers)
  * Group membership is not preserved when you reconnect
  * A connection can be a part of multiple groups
  * Groups are the recommended way for one connection to send to another connection (or connections)
  * Group names are case-sensitive
* Users
  * Use Users to manage all the connections associated with a single logical user
  * Adding a custom `IUserIdProvider` to DI allows you to change the "Identifier" used by SignalR (used in `Clients.User(...)` calls
  * User identifiers are case-sensitive.

**Closed** 2018-06-11 20:44 UTC
Labels: 2.1
