### ISSUE TITLE
SignalR Reconnect documentation

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#6757] opened 2018-05-31 19:17 UTC
We need to provide a sample and some guidance for reconnecting SignalR clients when they disconnect. See https://github.com/davidfowl/UT3/blob/dac409886c1bb7aec7c150b74d4ce9a3e246f03c/UTT/wwwroot/js/utt.js#L141-L153 for an example. The general idea is that you need to reconnect if 1) `connection.start` fails or 2) `connection.onclose` fires.

Reconnection should be limited to only a set number of retries so that the application doesn't keep trying to reconnect a broken connection forever.

**Comment by rachelappel** [comment] 2018-06-04 10:13
@anurse Add this to the clients docs?

**Comment by anurse** [comment] 2018-06-04 16:22
Yes

**Comment by anurse** [comment] 2018-06-28 16:14
I actually think this would be best as a new document: "Connection reliability in SignalR". We want to talk about:

* How to reconnect
* Reconnect backoff (trying to avoid reconnect storms by having the client reconnect at some random interval)
* Restoring state (groups, other metadata)
* Tracking a "logical" connection across different "physical" connections (session IDs, etc.)

**Comment by KirilRusev** [comment] 2018-09-06 16:01
Any news on this article?

**Comment by bradygaster** [comment] 2018-12-11 07:05
Closing as this doc exists for the most part [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.2).

**Comment by Rick-Anderson** [comment] 2019-01-19 03:32
@bradygaster 	can you assign someone to do this?

**Comment by bradygaster** [comment] 2019-01-22 23:03
@Rick-Anderson assigning the new-and-awesome SignalR label so we can triage these during our regular team triage.

**Comment by bradygaster** [comment] 2019-02-07 09:19
closing this as a duplicate of #9280, which would represent a superset of the desires of this particular issue.

**Closed by bradygaster** 2019-02-07 09:19 UTC
Labels: P1, SignalR
