### ISSUE TITLE
Snapshot code

### ISSUE THREAD

**Issue by lukos** [aspnet/Docs#7205] opened 2018-06-21 12:09 UTC
I don't think your IOptionsSnapshot example is quite correct. If you are taking the Value property in the Constructor and storing it, it will not update at runtime (although your example appears to be scoped, in which case the pattern is irrelevant). I think you should store the IOptionsSnapshot and simply call Value each time it is needed. This way, in a Singleton, you will always get the latest value of config.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2018-06-21 14:04
Hello @lukos ... I don't follow your reasoning based on the way that the scenario was developed by engineering. Options are computed once per request when accessed and cached for the lifetime of the request by design AFAIK. Let's play an exciting round of **_Ask the Engineer!_** :smile:

ping @HaoK

**Comment by lukos** [comment] 2018-06-21 14:19
My understanding (which is possibly not correct!) is that IOptionsSnapshot is designed to allow dynamic changes, which only has meaning for a singleton. If you get options bound per-request then surely you can just use IOptions<T> instead? I must admit I am not entirely clear about all the options interfaces!

**Comment by guardrex** [comment] 2018-06-21 14:43
Here's the [original info that Hao provided (aspnet/Docs \#3469)](https://github.com/aspnet/Docs/issues/3469#issuecomment-329875277) ...

> `IOptionsSnapshot<TOptions>` - This type was re-implemented in 2.0 with some subtle differences. In 1.x, this would be a snapshot of `IOptionsMonitor<TOptions>` and would update automatically whenever the monitor triggered changes. In 2.0, this was re-purposed to be used for options with the lifetime of the request. `TOptions` will be computed once per request, and cached for the lifetime of the request, but each request will get a new instance that will be recomputed the first time its asked for.

**Comment by lukos** [comment] 2018-06-21 14:54
So now I've seen some errors in my code, it is clear that IOptions is basically registered as a Singleton and IOptionsSnapshot is scoped and *cannot* be used in a Singleton for that reason. The bit I don't understand is that apart from the Get(string) which exists on IOptionsSnapshot, won't a *scoped* service behave identically with both interfaces since the service only lives for the duration of a request anyway and surely IOptions will also get the latest config next time round?

The only way I can think that it makes sense is if IOptions is somehow glued to the original config and never changes during the lifecycle of the application, even when passed to scoped or transient services that are created multiple times?

**Comment by guardrex** [comment] 2018-06-21 14:57
Yes, I think your interpretation is correct. `IOptionsSnapshot` will pick up an *underlying options source change* that `IOptions` won't pick up.

**Comment by lukos** [comment] 2018-06-21 15:01
OK thanks. I am thinking about writing my own article about options, it is quite complex and there are certain solutions that are hard to find from the documentation. For example, I need to register more than one config instance for 2 redis connections but without IOptionsSnapshot, I cannot call Get(string) except that I can with an IOptionsFactory, which is a dissimilar interface.

It would be nice to have a summary of the interfaces, which ones are basically internal and give you free functionality (that might be all of them) and which we need to register or implement in a certain way to achieve the functionality.

Thanks

**Comment by guardrex** [comment] 2018-06-21 15:03
Let's leave this open until we hear back from Hao. He might decide that the line ...

> In ASP.NET Core 2.0 and later, options are computed once per request when accessed and cached for the lifetime of the request.

... could use a touch of embellishment.

**Comment by guardrex** [comment] 2018-11-11 18:57
@HaoK I just put another :eye: on this issue and the topic: I *think* we're ok here with the content we have for `IOptionsSnapshot`, including the example in the sample app ...

> Options are computed once per request when accessed and cached for the lifetime of the request.
>
> The following example demonstrates how a new IOptionsSnapshot is created after appsettings.json changes (Pages/Index.cshtml.cs). Multiple requests to the server return constant values provided by the appsettings.json file until the file is changed and configuration reloads.

It appears in the topic at :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/configuration/options#reload-configuration-data-with-ioptionssnapshot

Do you concur? If not, what should be added so that I can close this issue out?

**Comment by Rick-Anderson** [comment] 2019-01-04 02:52
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Closed by Rick-Anderson** 2019-01-04 02:52 UTC
Labels: P3, Source - Docs.ms, question
