### ISSUE TITLE
document Identity UI  localize

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#11321] opened 2019-03-08 00:05 UTC
Provide an outline on what it currently takes to localize the Identity UI.  See https://github.com/aspnet/AspNetCore/issues/5838

@mduu  would you be able to provide this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment] 2019-03-23 15:17
@Rick-Anderson this is a duplicate of issue #11038

**Closed** 2019-03-24 05:43 UTC
Labels: P2, Source - Docs.ms
