### ISSUE TITLE
Out of date.

### ISSUE THREAD

**Issue by IainStevenson** [aspnet/Docs#9976] opened 2018-12-12 09:25 UTC
This document details obsolete Methods, e.g. services.AddSwagger(); and  app.UseSwaggerWithApiExplorer (...  

Please update to match the code base.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment] 2018-12-12 18:01
Closing as a duplicate of https://github.com/aspnet/Docs/issues/9631.

**Closed by scottaddie** 2018-12-12 18:01 UTC
Labels: Source - Docs.ms
