### ISSUE TITLE
There aren't any official document about jwt in web api

### ISSUE THREAD

**Issue by devSoheilAlizadeh** [aspnet/Docs#9438] opened 2018-11-05 16:18 UTC
The title is clear. I've checked the docs but I couldn't find anything about jwt or Authorize and Authentication in web api! While there are some middleware and service for them.

**Comment by Rick-Anderson** [comment] 2018-11-08 18:09
@devSoheilAlizadeh 	thanks for the suggestion. Closing as a duplicate of #4556

**Closed by Rick-Anderson** 2018-11-08 18:09 UTC
