### ISSUE TITLE
Data Annotations

### ISSUE THREAD

**Issue by steveoh** [aspnet/Docs#8087] opened 2018-08-14 22:56 UTC
I cannot get default values to show up in the json output. 

- I `EnableAnnotations()` in the `SwaggerGen` but it did not affect the output.
- I added the new annotations lib thinking that might help but it also did not affect the output.

Is https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/412 related?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml#data-annotations)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by steveoh** [comment] 2018-08-14 23:05
https://github.com/aspnet/Mvc/issues/7563

**Comment by Rick-Anderson** [comment] 2018-08-16 01:42
@steveoh  looks like aspnet/Mvc#7563 was fixed in PR https://github.com/aspnet/Mvc/pull/7957

You could open an issue in  https://github.com/aspnet/Mvc
Create the simplest possible app the reproduces the problem and share on a repo.

**Closed** 2019-01-04 01:01 UTC
Labels: P3, Source - Docs.ms
