### ISSUE TITLE
EF7/MVC 6 update of the Contoso University sample web app

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#849] opened 2016-01-04 20:11 UTC
http://www.asp.net/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application

Work will start about 22 Feb 2016 and will take 3 weeks to complete.
@tdykstra to lead effort.

**Comment by danroth27** [comment] 2016-05-19 05:56
@Rick-Anderson What does the Contoso University tutorial cover that the existing MVC tutorial we have doesn't cover?

**Comment by danroth27** [comment] 2016-05-19 05:57
Possible duplicate of https://github.com/aspnet/Docs/issues/977?

**Comment by tdykstra** [comment] 2016-05-19 15:27
The EF 6 MVC 5 CU tutorial series is a long one that covers a number of topics.  It's not a duplicate of 977 because one thing it doesn't cover is auth.  Beyond basic CRUD it covers related data extensively, data model attributes and fluent API extensively, connection resiliency, command interruption, stored procedures, concurrency, inheritance, performing raw SQL, no-tracking, debugging, and a number of other subjects related to working with relational data.

**Comment by tdykstra** [comment] 2016-09-22 22:00
Fixed by #1893

**Closed by tdykstra** 2016-09-22 22:00 UTC
Labels: 0 - Backlog, P1, topic
