### ISSUE TITLE
Your first Mac ASP.NET app tutorial problems

### ISSUE THREAD

**Issue by TravisTheTechie** [aspnet/Docs#173] opened 2015-04-30 01:00 UTC
1. Says should use 1.0.0-beta4. Can't install beta4 from the feed... `dnvm install 1.0.0-beta4` nor `dnvm install 1.0.0-beta4 -u`. (semi-related, where do I report that empty directories in `~/.dnx/runtimes` for failed installs is annoying?)
1. Screen shots don't match the current `generator-aspnet` options. 
1. Can't get the `dnu` commands to run from VS Code, but that might be an issue on my end. OmniSharp won't start up either and might be related. They do run from the command line, so good enough. 
1. Kestrel is already in the project.json
1. Bug in the beta5 version of Kestrel, have to `export MONO_MANAGED_WATCHER=false` or eat all the file descriptors. 
1. Kestrel just reports `TypeLoadException: Could not load type 'Microsoft.Framework.Runtime.ILibraryExport' from assembly 'Microsoft.Framework.Runtime.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.` when I try to load a page after `dnx . kestrel`.

**Comment by davidfowl** [comment] 2015-04-30 01:03
> Says should use 1.0.0-beta4. Can't install beta4 from the feed... dnvm install 1.0.0-beta4 nor dnvm install 1.0.0-beta4 -u. (semi-related, where do I report that empty directories in ~/.dnx/runtimes for failed installs is annoying?)

This should be fixed now. Installing beta4 should work /cc @glennc 

> Can't get the dnu commands to run from VS Code, but that might be an issue on my end. OmniSharp won't start up either and might be related. They do run from the command line, so good enough.

That is likely the problem. Omnisharp tells VSCode about the commands.

> Bug in the beta5 version of Kestrel, have to export MONO_MANAGED_WATCHER=false or eat all the file descriptors.

Nothing to do with Kestrel. It's a mono issue likely caused by Razor view compilation.

> Kestrel just reports TypeLoadException: Could not load type 'Microsoft.Framework.Runtime.ILibraryExport' from assembly 'Microsoft.Framework.Runtime.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. when I try to load a page after dnx . kestrel.

Sounds like you've mismatched beta4 and beta5 bits. They are incompatible.

**Comment by TravisTheTechie** [comment] 2015-04-30 01:20
So it sounds like beta4 is the source of all my issues. 

``` bash
$ brew update && brew upgrade
Already up-to-date.
$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11657    mono         ~/.dnx/runtimes      default
$ dnvm install 1.0.0-beta4
Downloading dnx-mono.1.0.0-beta4 from https://nuget.org/api/v2
Download: https://nuget.org/api/v2/package/dnx-mono/1.0.0-beta4
######################################################################## 100.0%
\e[0;31mHTTP Error 301 fetching dnx-mono.1.0.0-beta4 from https://nuget.org/api/v2 \e[0m
$ rm -rf ~/.dnx/runtimes/dnx-mono.1.0.0-beta4
$ dnvm install -u 1.0.0-beta4
dnvm install -u 1.0.0-beta4
Downloading dnx-mono.1.0.0-beta4 from https://www.myget.org/F/aspnetvnext/api/v2
Download: https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-mono/1.0.0-beta4
######################################################################## 100.0%
dnx-mono.1.0.0-beta4 was not found in repository https://www.myget.org/F/aspnetvnext/api/v2 
This is most likely caused by the feed not having the version that you typed. Check that you typed the right version and try again. Other possible causes are the feed doesn't have a DNX of the right name format or some other error caused a 404 on the server.
```

I also tried 1.0.0.0-beta4 per https://github.com/OmniSharp/generator-aspnet/issues/149#issuecomment-97622624

How do I get beta4 then?

**Comment by TravisTheTechie** [comment] 2015-04-30 01:29
https://www.nuget.org/packages/dnx-mono/1.0.0-beta4 exits, so, `dnvm install 1.0.0-beta4` should work, right? 

```
$ dnvm install latest
Determining latest version
Error: Could not find latest version from feed https://nuget.org/api/v2
```

Maybe that's the issue, something with nuget?

**Comment by TravisTheTechie** [comment] 2015-04-30 01:35
Lame...

```
$ open https://nuget.org/api/v2/package/dnx-mono/1.0.0-beta4
# ... wait for download
$ dnvm install ~/Downloads/dnx-mono.1.0.0-beta4.nupkg -p
Installing to /Users/tsmith/.dnx/runtimes/dnx-mono.1.0.0-beta4
Adding /Users/tsmith/.dnx/runtimes/dnx-mono.1.0.0-beta4/bin to process PATH
Setting alias 'default' to 'dnx-mono.1.0.0-beta4'
$ dnu restore
# ...
$ dnx . kestrel
```

And poof web pages load now without error pages.

**Comment by davidfowl** [comment] 2015-04-30 01:37
Nothing wrong with NuGet. Try dnvm update-self https://github.com/aspnet/dnvm/issues/235

**Closed** 2015-04-30 01:36 UTC

**Comment by kelong** [comment] 2015-05-01 16:49
@TravisTheTechie still same error after installing manually.
ulimit -n
65536
ulimit -u
709
IOException: kqueue() FileSystemWatcher has reached the maximum nunmber of files to watch.
System.IO.KqueueMonitor.Add (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>, line 0

**Comment by TravisTheTechie** [comment] 2015-05-01 17:29
Does `dnvm list` show beta4 as the default and active one? You might need to `dnvm use 1.0.0-beta4`. Still running into the mono issue with kestrel would indicate you're still using beta5.

**Comment by kelong** [comment] 2015-05-01 18:17
@TravisTheTechie I have never installed beta5 version.
dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta4          mono         ~/.dnx/runtimes      default
