### ISSUE TITLE
Generic Host example?

### ISSUE THREAD

**Issue by haydenhancock** [aspnet/Docs#8639] opened 2018-09-20 18:45 UTC
Is there a specific example that can be used for a generic Host instead of WebHost? I've found some useful information from other resources, however, I can't get it to work when utilizing appsettings.json. When attempting to start the Windows Service, I receive, "The service did not respond to the start or control request in a timely fashion." Any guidance would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment] 2018-09-20 18:52
Hello @haydenhancock ... Yes, there is a prototype (I think). Follow the link on the other issue pertaining to this. Your request is a duplicate of that, and we hope to get a Generic Host example for a WS put in the doc set.

Follow the link at: https://github.com/aspnet/Docs/issues/7040#issuecomment-405299104

Closing as a duplicate of #7040.

**Closed by guardrex** 2018-09-20 18:52 UTC
