### ISSUE TITLE
RC2 Source code

### ISSUE THREAD

**Issue by avikenjale** [aspnet/Docs#1508] opened 2016-06-24 20:27 UTC
RC2 documentation for [**"Managing Application state"**](https://docs.asp.net/en/latest/fundamentals/app-state.html), provides link for sample code, however when comes to GitHub, it is pointed to RC1 documentation. 
Please can you either update link or update source code compatible with RC2.

**Comment by danroth27** [comment] 2016-06-24 21:08
Duplicate of #1345

**Closed by danroth27** 2016-06-24 21:08 UTC
