### ISSUE TITLE
Add the SignalR client library doesn't work

### ISSUE THREAD

**Issue by carlos-ferreira** [aspnet/Docs#8823] opened 2018-10-03 09:29 UTC
I tried to follow the steps but the there are no files listed when selecting the option "Choose specific files:".
It seems that the package is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Tutorial: Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment] 2018-10-03 16:43
@carlos-ferreira There's an error in the way that step is rendered on the site - the underscores aren't part of what you enter:  enter  `aspnet/signalr@1`, not  `_@aspnet/signalr@1_`,  I'll fix the tutorial.

**Comment by tdykstra** [comment] 2018-10-03 16:52
@carlos-ferreira I've set up the PR that fixes the rendering problem to close this issue when the PR is merged; if it turns out the cause of your not seeing files in the package was something different, please feel free to  reopen the issue.  Thanks for pointing this out -- it probably tripped up other people as well.

**Closed** 2018-10-03 18:08 UTC
