### ISSUE TITLE
Developing for a Linux environment on Windows

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#245] opened 2015-05-18 18:06 UTC
Document setting up a Linux VM on hyper-v right through to running the app

**Comment by SpaceShot** [comment] 2015-08-21 17:56
I have been doing this in VirtualBox with Ubuntu desktop and currently working on CentOS (got DNVM/DNU/DNX going but dnu restore keeps timing out).  Is there any value in documenting VirtualBox.

The problem I've had with Hyper-V is that Ubuntu / HyperV has a known issue when you are on a wireless network (don't know the root cause, but found others with the problem).  Unfortunately, my home network is all wireless.  While I found workarounds, I couldn't get them to work well.  So I switched to VirtualBox to learn Linux and work with ASP.NET 5.

**Comment by SpaceShot** [comment] 2015-08-22 02:06
I think I was a little confused.  The problems I had were on Windows Server 2012 R2.  But on Windows 10 Hyper-V, Ubuntu is installing just fine and using a wireless network fine.  I am going to make sure this all works and then start documenting the process.

**Comment by Rick-Anderson** [comment] 2015-10-10 19:43
@SpaceShot  Hyper-V requires a wired connection. I use a cheap DLink DAP-1350 bridge to get Ethernet for my VMs.

**Comment by danroth27** [comment] 2016-05-19 06:23
@SteveLas How are you guys currently handling documentation for ASP.NET Core + VS + Docker on Windows? Is there something we can just reference from the ASP.NET Core docs?

**Comment by danroth27** [comment] 2016-05-19 06:24
I think we can just reference https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-docker-edit-and-refresh/

**Comment by SteveLasker** [comment] 2016-05-19 06:29
VirtualBox is a bit difficult. We've been focusing on the Docker for Windows beta. http://beta.docker.com It is a private beta, but they are accepting people regularly. Here's a writeup I did a bit ago. https://blogs.msdn.microsoft.com/stevelasker/2016/03/24/docker-for-windows-beta-released/ 
We do have a set of docks, which are listed on the download page: http://aka.ms/DockerToolsForVS which includes VirtualBox issues, amongst other things. That said, we do need more docs and we're working on a plan, with Docker as well to include ASP.NET Core docs in the http://docs.docker.com

Other than the VirutalBox issues, were there other docs you were interested in?

**Comment by spboyer** [comment] 2016-08-08 20:13
Can we close this issue? Docker on Windows appears to be pretty solid now.
@SteveLasker @danroth27

**Comment by SteveLasker** [comment] 2016-08-08 22:29
Yeah, we should start directing customers to Docker for Windows.

**Comment by spboyer** [comment] 2016-08-09 15:19
Please use this for developing on Windows: https://docs.docker.com/docker-for-windows/

**Closed by spboyer** 2016-08-09 15:19 UTC
Labels: 0 - Backlog, P2, topic
