### ISSUE TITLE
Can't build many sample projects

### ISSUE THREAD

**Issue by nicholasyin** [aspnet/Docs#8199] opened 2018-08-21 07:38 UTC
For example, i open the following sample code project using my latest VS:

Docs\aspnetcore\mvc\advanced\custom-model-binding\sample\CustomModelBindingSample

and found that i can't run it even using IIS Express. Screenshot as below:
![image](https://user-images.githubusercontent.com/17007651/44387408-05ee2b80-a558-11e8-8b8a-96a29f2d9f82.png)
This error has also showed up when I tried to launch some other sample code of Core. For reference here's my VS about:
![image](https://user-images.githubusercontent.com/17007651/44387453-25855400-a558-11e8-95c9-c6744036ddf1.png)

**Comment by guardrex** [comment] 2018-08-21 12:43
Hello @nicholasyin 

Just to make sure you have the correct SDK installed. Open a command prompt and execute `dotnet --version`. Does it report back `2.1.400`? If not, obtain and install the latest SDK from: https://www.microsoft.com/net/download

WRT the sample: This sample is a rather old 1.0-era sample. It's on the sample update tracking issue #5495. It may require an update to run. We'll get to it asap on #5495.

**Comment by guardrex** [comment] 2018-08-21 13:28
I'm going to close this as a duplicate of #5495. We can re-open the issue for further discussion if needed.

**Closed by guardrex** 2018-08-21 13:28 UTC
Labels: Duplicate

**Comment by nicholasyin** [comment] 2018-08-22 10:00
@guardrex 

![image](https://user-images.githubusercontent.com/17007651/44457245-4c658800-a635-11e8-8792-f1be1b705d26.png)

**Comment by guardrex** [comment] 2018-08-22 11:58
Good ... at least that's not the problem.

This particular sample is rather ancient by .NET Core standards. It probably won't run until it's updated, and we'll get to it as soon as we can on #5495.

If you'd like to try to upgrade it yourself locally, there are migration guides in the migration guides from 1.x to 2.0 at https://docs.microsoft.com/aspnet/core/migration#aspnet-core-1x-to-20.
