### ISSUE TITLE
'ISession' does not contain a definition for 'SetString'

### ISSUE THREAD

**Issue by Hypenate** [aspnet/Docs#7076] opened 2018-06-15 12:52 UTC
'ISession' does not contain a definition for 'SetString' and no extension method 'SetString' accepting a first argument of type 'ISession' could be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and application state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Hypenate** [comment] 2018-06-15 12:55
It works with this code:

```
public static class SessionExtensions
{
  public static void Set<T>(this ISession session, string key, T value)
  {
    session.Set<string>(key, JsonConvert.SerializeObject(value));
  }

  public static T Get<T>(this ISession session, string key)
  {
    var value = session.Get<string>(key);
    return value == null ? default(T) : JsonConvert.DeserializeObject<T>(value);
  }
}
```

**Comment by guardrex** [comment] 2018-06-15 15:00
Hello @Hypenate ... this topic and the sample ["samples" (plural) really, since there will be 1.x and 2.x samples] were just overhauled. The PR is in review, and the new topic should appear shortly. I'll close this as a duplicate of #5495. If you want to see the PR for the new topic where you'll find the new content in the app-state.md file, it's over here :point_right: https://github.com/aspnet/Docs/pull/7029

**Comment by Hypenate** [comment] 2018-06-15 17:33
In the [new documentation](https://github.com/aspnet/Docs/blob/5189f9b17bcc1505398d9598db049a9f554f11d9/aspnetcore/fundamentals/app-state/samples/2.x/SessionSample/Extensions/SessionExtensions.cs), the `SetString `is still there.
Yet it is unknown to `ISession`.

**Comment by guardrex** [comment] 2018-06-15 17:36
Ok ... Thanks. I'll take a look and get back to you soon.

**Comment by guardrex** [comment] 2018-06-15 18:04
@Hypenate Did you add a namespace for ...

```csharp
using Microsoft.AspNetCore.Http;
```

**Comment by Hypenate** [comment] 2018-06-15 18:15
@guardrex I copy pasted it from the [new documentation](https://github.com/aspnet/Docs/blob/5189f9b17bcc1505398d9598db049a9f554f11d9/aspnetcore/fundamentals/app-state/samples/2.x/SessionSample/Extensions/SessionExtensions.cs)

My ISession is: Assembly Microsoft.AspNetCore.Http.Features, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

**Comment by guardrex** [comment] 2018-06-15 18:30
I added some content that will indicate more info about what the `ISession` extension methods are, where they are, and how to get them.

https://github.com/aspnet/Docs/pull/7029/commits/05233d952dbd9f8de856bed64f2cecfa33a79cb2

For most devs using a vanilla 2.1 project that references `Microsoft.AspNetCore.App`, they'll just need to have a `using Microsoft.AspNetCore.Http;` statement in the class file to get access to the extension methods. 🤞

**Comment by Hypenate** [comment] 2018-06-18 08:39
I have added the Nugget _Microsoft.AspNetCore.Http.Extensions_ and then the code works!

**Comment by guardrex** [comment] 2018-06-18 12:46
Excellent @Hypenate. I made some further enhancements to the language in the PR to cover this issue.

**Closed** 2018-06-19 14:40 UTC
Labels: P2, Source - Docs.ms
