### ISSUE TITLE
Certificates and HTTPS

### ISSUE THREAD

**Issue by killnine** [aspnet/Docs#9355] opened 2018-10-31 13:56 UTC
Back in the summer I set up a aspnetcore 2.0 project and everything pretty much worked out of the box. Now I've set up a 2.1 project and Kestrel immediately complains about not having certificates installed as part of its move toward HTTPS by default. 

When not in a docker environment, this is fine. It's like 1 command to add the development certificates to work locally on your machine. But this issue isn't clearly explained, resolved, or automated when working with Docker.

What's the right path? Some say to not use HTTPS in docker (where your ingress point would strip off SSL for performance reasons) but I find that hard to believe as a best practice. Is there any way the documentation can discuss this?

Similar stackoverflow question: https://stackoverflow.com/questions/52167612/unable-to-create-a-dev-certificate-for-an-asp-net-core-web-app-in-a-docker-conta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment] 2018-10-31 16:22
Hello @killnine ... this is a duplicate of https://github.com/aspnet/Docs/issues/6199 (with a little bit more discussion, perhaps overlap, on https://github.com/aspnet/Docs/issues/3310). I'll close here, and you can track the work on #6199.

**Closed by guardrex** 2018-10-31 16:22 UTC
Labels: Source - Docs.ms
