### ISSUE TITLE
add Integration Testing chapter for the Contoso University example code

### ISSUE THREAD

**Issue by johanbove** [aspnet/Docs#3438] opened 2017-05-31 16:50 UTC
The ["Getting started with ASP.NET Core and Entity Framework Core using Visual Studio"](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/) series is a fantastic tutorial. First of all, thank you for creating this!

I've created this issue to request an additional chapter on "regression testing" the whole application, since I strongly believe this is a very important part of application development.

I found [the "regression testing" article](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing) by Steve Smith not complete enough to be able to integrate this back into the "Contoso University" application.

Unfortunately I lack the experience with aspnet to write this chapter of the tutorial myself.

Source of the referred "ef-mvc" demo app: ``/aspnet/Docs/tree/master/aspnetcore/data/ef-mvc``

Thank you.

**Comment by Rick-Anderson** [comment] 2017-05-31 22:20
@johanbove  Thanks for the suggestion. Hopefully we can find someone to write the topic or at least write the code. I've add the "up-for-grabs" label.

**Comment by Rick-Anderson** [comment] 2018-09-26 19:17
If [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) is missing information, it should be added there.

@daveabrock 	can you outline what you'd add to [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) ?

**Comment by daveabrock** [comment] 2018-09-26 19:38
I was thinking about adding a chapter to [this demo](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/?view=aspnetcore-2.1), with code pertaining to the demo code. I can reference back the [regression testing document](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1), and if while writing demo code I notice missing content I can add it there. Does that make sense, @Rick-Anderson?

**Comment by Rick-Anderson** [comment] 2018-09-26 19:59
@daveabrock 	I sure that doc would be welcomed by many developers, but I'm not convinced it's a good long term fit for our docs. I'd be more open to adding a section to  [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) and pointing to it from the [RP/EF](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/?view=aspnetcore-2.1) series.

@danroth27 	please review? Do we want a testing doc tightly coupled to the EF/RP tutorial **and** outside the testing TOC. Perhaps that would be better as a blog rather than maintained docs.

cc @tdykstra 	@scottaddie 	@guardrex

**Comment by guardrex** [comment] 2018-09-26 20:08
... and note that the *Integration tests* topic has undergone a major overhaul since this issue was opened (May 29; https://github.com/aspnet/Docs/pull/6086) and uses the new `WebApplicationFactory` approach for testing. The sample app covers the basic scenarios, and there are additional issues that might be addressed in future work on the topic ...

* How to create authenticated request? #6882
* How to assert against ApplicationDbContext #8713
* How to actually perform post requests? #7526

**Comment by daveabrock** [comment] 2018-09-26 20:55
All makes sense. I'll keep an eye on this. Until then, I see several open GitHub issues throughout the tutorial and maybe can take a look at some of those.

**Comment by guardrex** [comment] 2018-09-26 20:58
@daveabrock If you find a gap not covered by those existing issues for the *Integration tests* topic, open a new issue from the "Content feedback" button at the bottom of https://docs.microsoft.com/aspnet/core/test/integration-tests and we'll take a look.

**Comment by Rick-Anderson** [comment] 2018-09-26 21:05
> I see several open GitHub issues throughout the tutorial and maybe can take a look at some of those.

That would be great, thanks.

**Comment by daveabrock** [comment] 2018-09-26 21:08
Great @Rick-Anderson. I'll add an "on it!" comment on whatever I'm working on so you guys are aware.

**Comment by guardrex** [comment] 2018-12-13 00:06
@Rick-Anderson I was just sizing up the Integration Testing issues (and putting them into a project so that I don't lose track of them), and it looks like this one isn't actionable for the docs.

The ask is to add a topic on testing to a couple of the existing multi-topic tutorials (EF w/RP and/or EF w/MVC). That's not something that you wanted earlier.

There's nothing actionable here for the Integration Testing topic itself.

Therefore, this issue can be closed AFAICT.

**Closed** 2018-12-13 00:37 UTC
Labels: P3, topic, up-for-grabs

**Comment by jabbera** [comment] 2019-01-07 21:39
For those interested I build a package that makes this simple: https://github.com/jabbera/aspnetcore-testing-role-handler

Feedback welcomed.

**Comment by guardrex** [comment] 2019-01-07 21:48
@jabbera Nice piece. @jongalloway might be interested in mentioning this on the Standup, but it's easier for devs to consume it if they have a blog post that explains it all out. Are you planning to write something up for it?
