### ISSUE TITLE
Wrong: IIS must point to wwwroot.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Docs#1238] opened 2016-05-18 06:48 UTC
this doc is wrong. https://github.com/aspnet/Docs/blob/1.0.0-rc2/aspnet/hosting/directory-structure.rst

**Comment by danroth27** [comment] 2016-05-18 17:45
@shirhatti could you please take a look?

**Comment by shirhatti** [comment] 2016-06-01 18:01
Dupe of https://github.com/aspnet/Docs/issues/1305

**Closed by shirhatti** 2016-06-01 18:01 UTC
Labels: 1 - Ready, bug, P0
