### ISSUE TITLE
Reflecting CheckBox contents on the database - Tutorial Get started with EF Core in an ASP>NET MVC web app

### ISSUE THREAD

**Issue by PSCRIMS** [aspnet/Docs#11358] opened 2019-03-11 15:01 UTC
# Before you open an issue

If the issue is with an ASP.NET Core document, open the issue with the **Content feedback** button at the bottom of that document page.

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

{ description here }

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by guardrex** [comment] 2019-03-11 16:27
Isn't this a duplicate of https://github.com/aspnet/Docs/issues/11348.

btw @PSCRIMS ... If you use the **Content feedback** button at the bottom of the topic, it will tag the issue with metadata that helps us track the issue (and work if there will be a PR).

**Comment by PSCRIMS** [comment] 2019-03-11 18:02
Yes, it is a duplicate, I didn’t know how to reach the author and I do believe there is a problem with the code, thank you anyways.

 

Paul Rosemberg

**Comment by guardrex** [comment] 2019-03-11 18:08
Ok ... let's go with #11348. By mentioning it here, these issues are cross-linked now.

**Closed by guardrex** 2019-03-11 18:08 UTC

**Comment by PSCRIMS** [comment] 2019-03-11 18:11
Luke,

 

On 11358 I documented the steps to back my arguments that the code is at fault, could you please revert  your action to keep the most recent one?

 

Thanks in advance

 

Paul

**Comment by guardrex** [comment] 2019-03-11 18:15
> On 11358 I documented the steps to back my arguments that the code is at fault, could you please revert your action to keep the most recent one?

I'm confused. #11358 is **_this issue_**. The one with your steps and explanation is #11348.

#11358 - (this issue) closed
#11348 - open

Let me know if I'm 😵 ... I'm working on **_three things_** right now. ei ei ei 😅

**Comment by PSCRIMS** [comment] 2019-03-11 18:20
11358 Is the one that contains the explanation for my argument, with code copied from the tutorial, 11438 did not back my argument

 

Thanks,

 

Paul

**Comment by guardrex** [comment] 2019-03-11 18:34
#11358 is **this issue**, and the opening comment here is just the boilerplate.

**Comment by guardrex** [comment] 2019-03-12 17:49
There's no information here ... https://github.com/aspnet/Docs/issues/11358#issue-419517004 (the opening comment of this issue). It's just the boilerplate that we supply when a new issue is opened. It looks like you put the information in #11348, which is the issue that I left open.
