### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by nixonad** [aspnet/Docs#7074] opened 2018-06-15 12:06 UTC
According to the release notes and other blogs for asp dot net core 2.1, the cli tooling is now included in the 2.1 SDK and the DotNetCliToolReference updates are no longer relevant/necessary but this documentation has not been updated.
In addition it seems the 'new' default structure of program.cs (using the IWebHostBuilder) is not compatible with the EF tooling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [ASP.NET Core MVC with EF Core - Migrations - 4 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment] 2018-06-15 14:56
You're correct, @nixonad ... this topic is due for 2.1 updates on #5495. I'll close this as a duplicate of that issue, and we'll get to it asap. In the meantime, as you probably noticed, we have the migration topic at https://docs.microsoft.com/aspnet/core/migration/20_21 to tide folks over until the updates are complete.

**Closed by guardrex** 2018-06-15 14:56 UTC
